config/routes.rb
Rails.application.routes.draw do
  root to: 'questions#index'
  resources :questions do
    resources :answers
  end
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question

  validates :description, length: {minimum: 50}

  accepts_nested_attributes_for :question
end

app/models/question.rb
class Question < ActiveRecord::Base
  has_many :answers

  accepts_nested_attributes_for :answers

  validates :title, presence: true, length: { minimum: 40, message: "is too short. Must be 40 characters" }
  validates :description, presence: true, length: { minimum: 150, message: "is too short. Must be 150 characters" }
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  def new
    @answer = Answer.new
    @question = Question.find(params[:question_id])
  end

  def create
    @answer = Answer.create(question_id: params[:question_id], description: params[:answer][:description])
    @question = Question.find(params[:question_id])
    if @answer.save
      flash[:notice] = "Answer successfully submitted"
      redirect_to question_answers_path
    else
      render "new"
    end
  end

  def index
    @answers = Answer.where(question_id: params[:question_id])
  end



  private

  # def answer_params
  #   params.require(:answer).permit(:question_id, answer: :description)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def new
    @question = Question.new
  end

  def index
    @questions = Question.order(created_at: :desc).all
  end

  def show
    @question = Question.find(params[:id])
  end

  def create
    @question = Question.create(question_params)
    if @question.save
      flash[:notice] = "Question posted successfully."
      redirect_to question_path(@question)
    else
      render new_question_path
    end
  end

  def edit
    @question = Question.find(params[:id])
  end

  def update
    @question = Question.find(params[:id])
    @question.update(question_params)
    if @question.save
      flash[:notice] = "Question saved"
      redirect_to question_path(@question)
    else
      render "edit"
    end
  end

  def destroy
    Question.destroy(params[:id])
    if !@question
      flash[:notice] = "Question deleted"
      redirect_to "index"
    else
      render "show"
    end
  end

  private

  def question_params
    params.require(:question).permit(:title, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/answers/index.html.erb
<%= flash[:notice] %>
<% if @answers %>
  <% @answers.each do |answer| %>
    <div><%= answer.description %></div>
  <% end %>
<% end %>

app/views/answers/new.html.erb
<% if @answer.errors.any? %>
  <% @answer.errors.full_messages.each do |message| %>
    <div><%= message %></div>
  <% end %>
<% end %>

<%= form_for(@answer, :url => question_answers_path(@question)) do |f| %>
    <%= f.label :description, "Answer" %>
    <%= f.text_field :description %>
    <%= f.submit "Submit Answer" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RescueMission</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/questions/edit.html.erb
<% if @question.errors.any? %>
  <% @question.errors.full_messages.each do |msg| %>
    <div><%= msg %></div>
  <% end %>
<% end %>

<%= form_for @question do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :description %>
  <%= f.text_area :description %>
  <%= f.submit "Submit Question" %>
<% end %>

app/views/questions/index.html.erb
<ul id='questions'>
  <% @questions.each do |question| %>
    <li>
      <%= link_to(question.title, question_path(question))  %>
    </li>
  <% end %>
</ul>

app/views/questions/new.html.erb
<% if @question.errors.any? %>
  <% @question.errors.full_messages.each do |msg| %>
    <div><%= msg %></div>
  <% end %>
<% end %>

<%= form_for @question do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :description %>
  <%= f.text_area :description %>
  <%= f.submit "Submit Question" %>
<% end %>

app/views/questions/show.html.erb
<%= flash[:notice] %>

<%= @question.title %>
<%= @question.description %>
<%= link_to("Edit Question", edit_question_path(@question)) %>
<%= link_to("Delete Question", @question, method: :delete) %>

<%= link_to("Answer this Question", new_question_answer_path(@question)) %>
<%= link_to("View Answers", question_answers_path(@question)) %>

<% @question.answers.each do |answer| %>
  <%= answer.description %>
<% end %>